version: '2'
services:
    sampleproject-app:
        image: sampleproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sampleproject-postgresql:5432/SampleProject
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sampleproject-elasticsearch:9300
        ports:
            - 8080:8080
    sampleproject-postgresql:
        extends:
            file: postgresql.yml
            service: sampleproject-postgresql
    sampleproject-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sampleproject-elasticsearch
